### ISSUE TITLE
Cannot execute on CLI interface

### ISSUE THREAD

**Issue by tdh8316** [mbdevpl/transpyle#11]
Hi, I have trouble running on the command-line.

On Windows 10 and Anaconda, I installed it without [all] option.
And I executed this command:
```cmd
transpyle test.py --to-language Fortran95
```

The source file is super simple.
```python
# test.py
six = 3*2
```

And I got this error:
```cmd
transpyle [WARNING] C unavailable
Traceback (most recent call last):
  File "e:\anaconda\envs\attopython\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda\envs\attopython\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\envs\attopython\Scripts\transpyle.exe\__main__.py", line 9, in <module>
  File "e:\anaconda\envs\attopython\lib\site-packages\transpyle\main.py", line 108, in main
    raise NotImplementedError('printing to stdout not supported yet')
NotImplementedError: printing to stdout not supported yet
```

Never did I write anything that uses stdout. And I indeed have no clue why this occurred.
Is this related to the [all] option?

**Comment by mbdevpl** [comment]
Oh, the errors indeed could be more helpful here. The error comes from the transpiler, and the fact that currently it does not support printing translation results to stdout. You need to provide target path for translation. For example:

```
transpyle test.py test.f90 --to-language Fortran95
```

But then, also automatic language detection currently is not implemented yet, so what you need is fully specify everything. In addition, "Fortran95" is not registered at that name, you should use "Fortran 95" or just "Fortran". For example:

```
transpyle test.py test.f90 --from Python --to Fortran
```

I know it's a bit cumbersome... I'll definitely improve error reporting in the next release!

**Comment by mbdevpl** [comment]
The [all] option is not related, but please make sure to install with at least [fortran] option so that generating Fortran works!

**Comment by mbdevpl** [comment]
If in doubt, please double-check the output of: `transpyle --langs` it should show ticks next to Fortran support - also please use the output from there as a guideline for what languages and under what exact names are supported. I'll improve the error reporting on missing language name in the next release as well.

**Comment by tdh8316** [comment]
Thanks for your answer. It worked after providing the target path!
