### ISSUE TITLE
Installation via pip not working

### ISSUE THREAD

**Issue by ishandutta2007** [mbdevpl/transpyle#5]
`pip3 install transpyle`

> Collecting transpyle
>   Could not find a version that satisfies the requirement transpyle (from versions: )
> No matching distribution found for transpyle
> 

OS-X10.13
Python 3.4.2

**Comment by mbdevpl** [comment]
Thanks for trying out transpyle! Sorry, as specified in the requirements (https://github.com/mbdevpl/transpyle#requirements), transpyle needs Python 3.5. Is upgrading your Python an option?

**Comment by ishandutta2007** [comment]
Thanks for the quick reply. No problems I will switch to 3.6 for this proj. My bad I didn't read doc carefullly enough.

**Comment by ishandutta2007** [comment]
I am looking for C++ to Python transpiler.
Python to C++ might be easy as Cython does it and moreover Python itself is written in C++, so its essentially just revealing undelying code.

But how much of C++ to Python is possible? Is AST method enough? I was thinking of maybe there would be ML based solution to do it.

@mbdevpl we can close this issue, and if you don't mind would love to connect with you on Instant Messanger or somewhere,

Here are my contact details:

- google hangout/gmail: ishandutta2007@gmail.com
- whatsapp: +919952917263
- wechat: ishandutta2007offi
- linkedin https://www.linkedin.com/in/ishandutta2007
